### ISSUE TITLE
Minor typos 

### ISSUE THREAD

**Issue by ssesnie** [RCBlackburn/lidRmts#1]
Hi Ryan, this is a helpful package that I discovered looking for help with Lidar voxels in R. I found a few typos. You have 'kable' written in a few of the code examples that should be 'table'. Also in the voxel example using pixel_metrics you should have the following: 

v_metrics <- pixel_metrics(las_vox, func = vox_sum_raster(SVi, FRDi, PDi, PDi_above, vox_res = 2), res = 20)

in place of: 

v_metrics <- pixel_metrics(las_vox, func = vox_sum_raster(SVi_2, FRDi_2, PDi_2, PDi_above_2, vox_res = 2), res = 20)

to read the metrics in the 'las_vox' data created.

**Comment by RCBlackburn** [comment]
Hi Steve, thanks for pointing those out. I know this is an old comment, but I finally got around to revamping the package. There were some issues with a hodgepodge of updates and changes in naming structures. For this new update I've standardized the naming convention, wrapped some functions together, and added some new voxel metrics to the voxel_summary() and voxel_raster() functions. The README file has also been revised for the new functions. If you end up using it and find any issues, please let me know.

Also, I am using the kable function from the knitr package to view the outputs. 

Cheers!

**Comment by ssesnie** [comment]
[like]  Sesnie, Steven reacted to your message:
________________________________
From: RCBlackburn ***@***.***>
Sent: Tuesday, May 21, 2024 11:38:03 PM
To: RCBlackburn/lidRattR ***@***.***>
Cc: Sesnie, Steven ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [RCBlackburn/lidRattR] Minor typos (Issue #1)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Hi Steve, thanks for pointing those out. I know this is an old comment, but I finally got around to revamping the package. There were some issues with a hodgepodge of updates and changes in naming structures. For this new update I've standardized the naming convention, wrapped some functions together, and added some new voxel metrics to the voxel_summary() and voxel_raster() functions. The README file has also been revised for the new functions. If you end up using it and find any issues, please let me know.

Also, I am using the kable function from the knitr package to view the outputs.

Cheers!

**Comment by ssesnie** [comment]
Thanks Ryan, I will check it out.


--
Steven E. Sesnie, Ph.D.<https://scholar.google.com/citations?hl=en&user=UA63fckAAAAJ&view_op=list_works&sortby=pubdate> (he/him)
Guest editor for Remote Sensing Special Issue: "Wildlife Ecology for a Dynamic Future"
https://www.mdpi.com/journal/remotesensing/special_issues/RS_Wildlife_Ecology

Spatial Ecologist
U.S. Fish & Wildlife Service
Southwest Region
P.O. Box 1306
Albuquerque, NM 87103-1306
505-248-6631 office
505-280-9903 cell
505-248-6460 fax
________________________________
From: RCBlackburn ***@***.***>
Sent: Tuesday, May 21, 2024 5:38 PM
To: RCBlackburn/lidRattR ***@***.***>
Cc: Sesnie, Steven ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [RCBlackburn/lidRattR] Minor typos (Issue #1)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Hi Steve, thanks for pointing those out. I know this is an old comment, but I finally got around to revamping the package. There were some issues with a hodgepodge of updates and changes in naming structures. For this new update I've standardized the naming convention, wrapped some functions together, and added some new voxel metrics to the voxel_summary() and voxel_raster() functions. The README file has also been revised for the new functions. If you end up using it and find any issues, please let me know.

Also, I am using the kable function from the knitr package to view the outputs.

Cheers!
